### ISSUE TITLE
您好，请问您的gitpages是如何做的呀，我想学习一下~

### ISSUE THREAD

**Issue by ki-chan-iine** [vxhly/vxhly.github.io#1]
您好，请问您的gitpagges是如何做的呀？写文章的时候是如何生成的index.html文件的呀？可以分享一下嘛？谢谢！

**Comment by vxhly** [comment]
该博客使用的是 [vuepress](https://vuepress.vuejs.org/) 框架加上 [reco](https://vuepress-theme-reco.recoluan.com/) 主题搭建而成，至于 gitpagges 依赖于 GitHub 的 page 服务，使用的是GitHub 的 actions 自动构建流程构建，所有的源代码在本仓库里面均可以找到

**Comment by vxhly** [comment]
关于 vuepress 的搭建和配置过程，博客中也已经有相应的文章了，可以自行搜索 vuepress 关键词进行查阅
